name: Deploy static content to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Build
        env:
          VITE_LIBSQL_DB_URL: ${{ secrets.VITE_LIBSQL_DB_URL }}
          VITE_LIBSQL_DB_TOKEN: ${{ secrets.VITE_LIBSQL_DB_TOKEN }}
          VITE_MASTER_LICENSE_KEY: ${{ secrets.VITE_MASTER_LICENSE_KEY }}
          VITE_ENCRYPTION_PASSWORD: ${{ secrets.VITE_ENCRYPTION_PASSWORD }}
          VITE_ENCRYPTION_SALT: ${{ secrets.VITE_ENCRYPTION_SALT }}
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
